### PR TITLE
Add llucax (myself) to the FUNDING.yml file

### PR DESCRIPTION
**Pull request by llucax**

### CODE REVIEW

**Comment by llucax** [comment]
Assigned @daniel-zullo-sociomantic because he is the only other contributor to this repo :)

**Comment by ben-palmer-sociomantic** [comment]
You might want to saw "Assign llucax ..." rather than "Assign myself ..." to be a bit clearer for other people :)

**Comment by llucax** [comment]
Do you mean in the commit message? If so I thought me being the author made it clear enough, but I can do that too.

**Comment by ben-palmer-sociomantic** [comment]
Yeah I did, not a biggie though just found it a bit funny.

**Comment by llucax** [comment]
Updated.

**Review by ibuclaw — APPROVED** [review]

**Review by daniel-zullo — APPROVED** [review]
LGTM

**Pull request merged**
